### ISSUE TITLE
Broken example : example_oauth.html

### ISSUE THREAD

**Issue by marcoscaceres** [spazproject/spazcore#9]
example_oauth.html points to ../vendors/jquery-1.3.2.js, should be "../vendors/jquery-1.4.2.js"

**Comment by funkatron** [comment]
Sure. feel free to fork and submit a pull req.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by marcoscaceres** [comment]
I guess this is no longer relevant.
